### ISSUE TITLE
「Generics、了解！」を収録してほしい

### ISSUE THREAD

**Issue by KisaragiEffective** [IBM/japan-technology#11]
こんにちは、そしてはじめまして。
フィードバックを提供するためにissueを作成してくださいとあったので失礼します。
個人的な願望ですが、Javaのジェネリクスの紹介で、「Generics、了解！」が[割と参照されている](https://www.google.com/search?q=%22Generics%E3%80%81%E4%BA%86%E8%A7%A3%EF%BC%81%22&client=ubuntu)ため、できれば収録していただきたいです。もし叶うのであれば、大変喜ばしいことだと思います。

要件のみですが失礼致します。お忙しい中、目をお通しくださりありがとうございました。

**Comment by tty-kwn** [comment]
@KisaragiEffective 
issueの登録ありがとうございます。
そして返答が遅くなってしまい、大変申し訳なく思っています。

ご要望のページですが、PDFではありますが、サルベージできました。
他にもいろいろJava系の資料を入手できましたので、readme.mdに一覧を書いて一緒に公開しようと思います。
近く公開しますので、もう少しお時間をください。

**Comment by KisaragiEffective** [comment]
ありがとうございます。
大変嬉しいと感じます。公開されるのを心待ちにしております。

**Comment by tty-kwn** [comment]
@KisaragiEffective 
旧developerWorks Japanで公開されていたJava Technologyの日本語資料について、一部を以下に復元しました。
https://github.com/IBM/japan-technology/tree/main/developerWorks/java

ぜひ、内容をご確認いただければと存じます。

**Comment by tty-kwn** [comment]
他に気になる資料がありましたらお声がけ(=issue起票)ください。

**Comment by KisaragiEffective** [comment]
@tty-kwn ありがとうございました！
